# Generated by Django 5.0.1 on 2024-02-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='space',
            field=models.FloatField(verbose_name='Площадь'),
        ),
    ]
