# Generated by Django 5.0.1 on 2024-02-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0003_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='logo',
            field=models.ImageField(blank=True, default='/media/defaults/default.png', null=True, upload_to='logos_of_Renters/%Y/%m/%d'),
        ),
    ]
