# Generated by Django 5.0.1 on 2024-03-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0007_alter_property_options_alter_request_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rent_app.renter', verbose_name='Арендодатель'),
        ),
    ]
