# Generated by Django 5.0.1 on 2024-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0008_alter_property_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Рассматривается', 1), ('Отклоненна', 0), ('Одобрена', 2)], default=1, max_length=32, verbose_name='Статус'),
        ),
    ]
