# Generated by Django 5.0.1 on 2024-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0009_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(1, 'Рассматривается'), (0, 'Отклонена'), (2, 'Одобрена')], default=1, max_length=32, verbose_name='Статус'),
        ),
    ]
